//! `pixi-mise.lock` read/write and sha256 helpers.

use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::CoreError;

/// One locked tool install for a platform.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LockEntry {
    /// Tool id (`github:owner/repo`).
    pub id: String,
    /// Concrete version string.
    pub version: String,
    /// GitHub tag name.
    pub tag: String,
    /// Asset filename.
    pub asset: String,
    /// Download URL.
    pub url: String,
    /// Checksum (`sha256:…`), when known.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
    /// Pixi platform key (`linux-64`, …).
    pub platform: String,
    /// Binaries installed into the prefix.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub installed_bins: Vec<String>,
}

/// Full lockfile document.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Lockfile {
    /// Locked tools (one entry per tool+platform).
    #[serde(default)]
    pub tools: Vec<LockEntry>,
}

impl Lockfile {
    /// Path to the workspace lockfile beside `pixi.toml`.
    pub fn workspace_path(workspace_root: &Path) -> PathBuf {
        workspace_root.join("pixi-mise.lock")
    }

    /// Path to the global lockfile under `$PIXI_HOME`.
    pub fn global_path(pixi_home: &Path) -> PathBuf {
        pixi_home.join("pixi-mise.lock")
    }

    /// Load a lockfile, or empty if missing.
    pub fn load(path: &Path) -> Result<Self, CoreError> {
        if !path.is_file() {
            return Ok(Self::default());
        }
        let text = fs::read_to_string(path).map_err(|e| CoreError::Config(e.to_string()))?;
        toml::from_str(&text).map_err(|e| CoreError::Config(format!("parse lockfile: {e}")))
    }

    /// Write the lockfile (pretty TOML).
    pub fn save(&self, path: &Path) -> Result<(), CoreError> {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).map_err(|e| CoreError::Config(e.to_string()))?;
        }
        let mut sorted = self.clone();
        sorted
            .tools
            .sort_by(|a, b| a.id.cmp(&b.id).then_with(|| a.platform.cmp(&b.platform)));
        let rendered =
            toml::to_string_pretty(&sorted).map_err(|e| CoreError::Config(e.to_string()))?;
        let header = "# This file is automatically @generated by pixi-mise.\n\
                      # It is not intended for manual editing.\n";
        fs::write(path, format!("{header}{rendered}"))
            .map_err(|e| CoreError::Config(e.to_string()))?;
        Ok(())
    }

    /// Find an entry for `id` + `platform`.
    pub fn find(&self, id: &str, platform: &str) -> Option<&LockEntry> {
        self.tools
            .iter()
            .find(|t| t.id == id && t.platform == platform)
    }

    /// Upsert an entry (replace same id+platform).
    pub fn upsert(&mut self, entry: LockEntry) {
        if let Some(existing) = self
            .tools
            .iter_mut()
            .find(|t| t.id == entry.id && t.platform == entry.platform)
        {
            *existing = entry;
        } else {
            self.tools.push(entry);
        }
    }

    /// Remove entries for a tool id (all platforms).
    pub fn remove_id(&mut self, id: &str) {
        self.tools.retain(|t| t.id != id);
    }
}

/// Compute `sha256:<hex>` for a file.
pub fn sha256_file(path: &Path) -> Result<String, CoreError> {
    let mut file = fs::File::open(path).map_err(|e| CoreError::Install(e.to_string()))?;
    let mut hasher = Sha256::new();
    let mut buf = [0u8; 64 * 1024];
    loop {
        let n = file
            .read(&mut buf)
            .map_err(|e| CoreError::Install(e.to_string()))?;
        if n == 0 {
            break;
        }
        hasher.update(&buf[..n]);
    }
    Ok(format!("sha256:{:x}", hasher.finalize()))
}

/// Verify a file against an expected `sha256:…` digest.
pub fn verify_sha256(path: &Path, expected: &str) -> Result<(), CoreError> {
    let actual = sha256_file(path)?;
    if !actual.eq_ignore_ascii_case(expected) {
        return Err(CoreError::Install(format!(
            "checksum mismatch for {}: expected {expected}, got {actual}",
            path.display()
        )));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn lockfile_roundtrip() {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("pixi-mise-lock-{nanos}"));
        fs::create_dir_all(&dir).unwrap();
        let path = dir.join("pixi-mise.lock");
        let mut lock = Lockfile::default();
        lock.upsert(LockEntry {
            id: "github:cli/cli".into(),
            version: "2.67.0".into(),
            tag: "v2.67.0".into(),
            asset: "gh_2.67.0_linux_amd64.tar.gz".into(),
            url: "https://example.com/gh.tgz".into(),
            checksum: Some("sha256:abc".into()),
            platform: "linux-64".into(),
            installed_bins: vec!["gh".into()],
        });
        lock.save(&path).unwrap();
        let loaded = Lockfile::load(&path).unwrap();
        assert_eq!(loaded.tools.len(), 1);
        assert_eq!(
            loaded.find("github:cli/cli", "linux-64").unwrap().version,
            "2.67.0"
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn sha256_stable() {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let path = std::env::temp_dir().join(format!("pixi-mise-sha-{nanos}"));
        {
            let mut f = fs::File::create(&path).unwrap();
            f.write_all(b"hello").unwrap();
        }
        let digest = sha256_file(&path).unwrap();
        assert_eq!(
            digest,
            "sha256:2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
        );
        verify_sha256(&path, &digest).unwrap();
        let _ = fs::remove_file(&path);
    }
}
